apiVersion: v1
kind: Secret
metadata:
  name: clashvers-secrets
  namespace: clashvers
type: Opaque
stringData:
  SUPABASE_URL: "your_supabase_url"
  SUPABASE_ANON_KEY: "your_anon_key"
  JWT_SECRET: "your_jwt_secret"
